### ISSUE TITLE
Would you like to migrate this repository into the cerebro organization? 

### ISSUE THREAD

**Issue by oguhpereira** [cerebroapp/cerebro-brew#2]
We are centralizing cerebro plugins in the product organization. It would be great to have this repository within the organization, to be part of the future plugin marketplace. If you are interested, we can create a team so that you can work directly on the project and help us grow this product.

See more https://github.com/cerebroapp

**Comment by oguhpereira** [comment]
Hi @luisdavim 
what can you tell me about this migration?

**Comment by luisdavim** [comment]
Hi, happy to move the repo, I haven't touched it in a while...

**Comment by oguhpereira** [comment]
Thank's @luisdavim 

I just sent the invite to you from the organization. There you can help us maintain this repository.

![image](https://user-images.githubusercontent.com/24482087/188017330-905b17ad-c32c-4fd7-a82f-b9c3f863efef.png)

Validate your email or go to the organization page, as the invite must be there.

**Comment by luisdavim** [comment]
Thanks, I've transferred the repository.
